# Generated by Django 3.1.3 on 2020-11-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(upload_to=None, verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, verbose_name='Est disponible')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.user', verbose_name='Annonceur')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Libellé')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('ads', models.ManyToManyField(to='advert.Ad', verbose_name="Liste d'annonces")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(to='advert.Category', verbose_name='Catégories'),
        ),
        migrations.AddField(
            model_name='ad',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='panel.enterprise', verbose_name='Compagnie'),
        ),
    ]
