# Generated by Django 3.1.3 on 2020-11-14 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_ad_sponsorised'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='category',
            name='ads',
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advert.category', verbose_name='Catégorie'),
        ),
    ]
