# Generated by Django 3.1.3 on 2020-11-14 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20201114_1939'),
        ('advert', '0003_auto_20201114_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.profile', verbose_name='Annonceur'),
        ),
    ]
