# Generated by Django 3.1.3 on 2020-11-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0006_auto_20201119_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=40),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='static/images/ads/', verbose_name='Image'),
        ),
    ]
