# Generated by Django 3.1.3 on 2020-11-19 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0004_auto_20201117_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='has_company',
        ),
        migrations.AddField(
            model_name='enterprise',
            name='avatar',
            field=models.ImageField(max_length=200, null=True, upload_to='static/images/avatar/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='enterprise',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrateur'),
        ),
    ]
